export const homes = [
  { id: 1, src: '/images/gucci.jpg', name: 'Gucci PG', info: 'Lançamento Gucci PG - Grupo FP OFICIAL.', link: 'https://5guccipg.com/?id=251859702&currency=BRL&type=2' },
  { id: 2, src: '/images/fplv.jpg', name: 'FPLV PG', info: 'Lançamento FPLV PG - Grupo FP OFICIAL.', link: 'https://7fplvpg.com/?id=623401615&currency=BRL&type=2' },
  { id: 3, src: '/images/chanel.jpg', name: 'Chanel PG', info: 'Lançamento Chanel PG - Grupo FP OFICIAL', link: 'https://5chanelpg.com/?id=495349000&currency=BRL&type=2' },
  { id: 4, src: '/images/ysl.jpg', name: 'Ysl PG', info: 'Lançamento Ysl PG - Grupo FP OFICIAL', link: 'https://7yslpg.com/?id=189113813&currency=BRL&type=2' },
  { id: 5, src: '/images/benz.jpg', name: 'Benz PG', info: 'Lançamento Benz PG - Grupo FP OFICIAL', link: 'https://7benzpg.com/?id=501716623&currency=BRL&type=2' },
  { id: 6, src: '/images/audi.jpg', name: 'Audi PG', info: 'Lançamento Audi PG - Grupo FP OFICIAL', link: 'https://7audipg.com/?id=776653851&currency=BRL&type=2' },
  { id: 7, src: '/images/hermes.jpg', name: 'Hermes PG', info: 'Lançamento Hermes PG - Grupo FP OFICIAL', link: 'https://www.7hermespg.com/?id=683669648&currency=BRL&type=2' },
  { id: 8, src: '/images/million.jpg', name: 'Million PG', info: 'Lançamento Million PG - Grupo FP OFICIAL', link: 'https://www.11millionpg.com/?id=441953721&currency=BRL&type=2' },
  { id: 9, src: '/images/gloss.jpg', name: 'Gloss PG', info: 'Lançamento Gloss PG - Grupo FP OFICIAL', link: 'https://2glosspg.com/?id=920523529&currency=BRL&type=2' },
  { id: 10, src: '/images/eiffel.jpg', name: 'Eiffel PG', info: 'Lançamento Eiffel PG - Grupo FP OFICIAL.', link: 'https://1eiffelwin.com/?id=341489336&currency=BRL&type=2' },
  { id: 11, src: '/images/pascoa.jpg', name: 'Pascoa PG', info: 'Lançamento Pascoa PG - Grupo FP OFICIAL.', link: 'https://1pascoawin.com/?id=950609492&currency=BRL&type=2' },
  { id: 12, src: '/images/cocacola.jpg', name: 'CocaCola PG', info: 'Lançamento CocaCola PG - Grupo FP OFICIAL.', link: 'https://www.7cocacolapg.com/?id=566232176&currency=BRL&type=2' },
  { id: 13, src: '/images/vinho.jpg', name: 'Vinho PG', info: 'Lançamento Vinho PG - Grupo FP OFICIAL.', link: 'https://www.6vinhopg.com/?id=161550618&currency=BRL&type=2' },
  { id: 14, src: '/images/flor.jpg', name: 'Flor PG', info: 'Lançamento Flor PG - Grupo FP OFICIAL.', link: 'https://3flor777.com/?id=776590383&currency=BRL&type=2' },
  { id: 15, src: '/images/lancha.jpg', name: 'Lancha PG', info: 'Lançamento Lancha PG - Grupo FP OFICIAL.', link: 'https://7lanchapg.com/?id=580535113&currency=BRL&type=2' },
  { id: 16, src: '/images/surfista.jpg', name: 'Surfista PG', info: 'Lançamento Surfista PG - Grupo FP OFICIAL.', link: 'https://7surfistapg.com/?id=635331078&currency=BRL&type=2' },
  { id: 17, src: '/images/norte.jpg', name: 'Norte PG', info: 'Lançamento Norte PG - Grupo FP OFICIAL.', link: 'https://3nortewin.com/?id=154120365&currency=BRL&type=2' },
  { id: 18, src: '/images/gratidao.jpg', name: 'Gratidão PG', info: 'Lançamento Gratidão PG - Grupo FP OFICIAL.', link: 'https://2gratidaobet.com/?id=340000470&currency=BRL&type=2' },
  { id: 19, src: '/images/aeronave.jpg', name: 'Aeronave PG', info: 'Lançamento Aeronave PG - Grupo FP OFICIAL.', link: 'https://2aeronavewin.com/?id=544061787&currency=BRL&type=2' },
  { id: 20, src: '/images/cisne.jpg', name: 'Cisne PG', info: 'Lançamento Cisne PG - Grupo FP OFICIAL.', link: 'https://3cisnewin.com/?id=389133202&currency=BRL&type=2' },
  { id: 21, src: '/images/ufo.jpg', name: 'Ufo PG', info: 'Lançamento Ufo PG - Grupo FP OFICIAL.', link: 'https://2ufopgbet.com/?id=212028612&currency=BRL&type=2' },
  { id: 22, src: '/images/suco.jpg', name: 'Suco PG', info: 'Lançamento Suco PG - Grupo FP OFICIAL.', link: 'https://7sucowin.com/?id=321154898&currency=BRL&type=2' },
  { id: 23, src: '/images/borboleta.jpg', name: 'Borboletas PG', info: 'Lançamento Borboletas PG - Grupo FP OFICIAL.', link: 'https://1borboletaswin.com/?id=688617817&currency=BRL&type=2' },
  { id: 24, src: '/images/pagode.jpg', name: 'Pagode PG', info: 'Lançamento Pagode PG - Grupo FP OFICIAL.', link: 'https://7pagodepg.com/?id=409040346&currency=BRL&type=2' },
  { id: 25, src: '/images/shein.jpg', name: 'Shein PG', info: 'Lançamento Shein PG - Grupo FP OFICIAL.', link: 'https://2sheinbet.com/?id=753288195&currency=BRL&type=2' },
  { id: 26, src: '/images/baby.jpg', name: 'Baby PG', info: 'Lançamento Baby PG - Grupo FP OFICIAL.', link: 'https://babybetpg.com/?id=214772019&currency=BRL&type=2' },
  { id: 27, src: '/images/rainha.jpg', name: 'Rainhas PG', info: 'Lançamento Rainhas PG - Grupo FP OFICIAL.', link: 'https://5rainhaspg.com/?id=588381879&currency=BRL&type=2' },
  { id: 28, src: '/images/porsche.jpg', name: 'Porsche PG', info: 'Lançamento Porsche PG - Grupo FP OFICIAL.', link: 'https://5porschepg.com/?id=955179798&currency=BRL&type=2' },
  { id: 29, src: '/images/mami.jpg', name: 'Mami PG', info: 'Lançamento Mami PG - Grupo FP OFICIAL.', link: 'https://5mamipg.com/?id=931471365&currency=BRL&type=2' },
  { id: 30, src: '/images/suv.jpg', name: 'Suv PG', info: 'Lançamento Suv PG - Grupo FP OFICIAL.', link: 'https://5suvpg.com/?id=286401412&currency=BRL&type=2' },
  { id: 31, src: '/images/princesa.jpg', name: 'Princesa PG', info: 'Lançamento Princesa PG - Grupo FP OFICIAL.', link: 'https://princesawin.com/?id=626625863&currency=BRL&type=2' },
  { id: 32, src: '/images/jeep.jpg', name: 'Jeep PG', info: 'Lançamento Jeep PG - Grupo FP OFICIAL.', link: 'https://jeep2024.com/?id=136416274&currency=BRL&type=2' },
  { id: 33, src: '/images/iphone.jpg', name: 'Iphone PG', info: 'Lançamento Iphone PG - Grupo FP OFICIAL.', link: 'https://1iphonebetpg.com/?id=913308160&currency=BRL&type=2' },
  { id: 34, src: '/images/samsung.jpg', name: 'Samsung PG', info: 'Lançamento Samsung PG - Grupo FP OFICIAL.', link: 'https://1samsungwin.com/?id=120835107&currency=BRL&type=2' },
  { id: 35, src: '/images/mulher.jpg', name: 'Mulher PG', info: 'Lançamento Mulher PG - Grupo FP OFICIAL.', link: 'https://1mulherbetpg.com/?id=995521334&currency=BRL&type=2' },
  { id: 36, src: '/images/whisky.jpg', name: 'Whisky PG', info: 'Lançamento Whisky PG - Grupo FP OFICIAL.', link: 'https://whiskybetpg.com/?id=197336658&currency=BRL&type=2' },
  { id: 37, src: '/images/pulseira.jpg', name: 'Pulseira PG', info: 'Lançamento Pulseira PG - Grupo FP OFICIAL.', link: 'https://1pulseirawin.com/?id=363079617&currency=BRL&type=2' },
  { id: 38, src: '/images/manicure.jpg', name: 'Manicure PG', info: 'Lançamento Manicure PG - Grupo FP OFICIAL.', link: 'https://manicurewin.com/?id=984155348&currency=BRL&type=2' },
  { id: 39, src: '/images/euteamo.jpg', name: 'Eu te amo PG', info: 'Lançamento Eu te amo PG - Grupo FP OFICIAL.', link: 'https://3euteamopg.com/?id=436368150&currency=BRL&type=2' },
  { id: 40, src: '/images/donuts.jpg', name: 'Donuts PG', info: 'Lançamento Donuts PG - Grupo FP OFICIAL.', link: 'https://3donutspg.com/?id=613311144&currency=BRL&type=2' },
  { id: 41, src: '/images/pikachu.jpg', name: 'Pickachu PG', info: 'Lançamento Pickachu PG - Grupo FP OFICIAL.', link: 'https://3pikachupg.com/?id=171345151&currency=BRL&type=2' },
  { id: 42, src: '/images/vida.jpg', name: 'Vida PG', info: 'Lançamento Vida PG - Grupo FP OFICIAL.', link: 'https://3vidapg.com/?id=489965773&currency=BRL&type=2' },
  { id: 43, src: '/images/ursinho.jpg', name: 'Ursinho PG', info: 'Lançamento Ursinho PG - Grupo FP OFICIAL.', link: 'https://3ursinhopg.com/?id=193955846&currency=BRL&type=2' },
  { id: 44, src: '/images/brinco.jpg', name: 'Brinco PG', info: 'Lançamento Brinco PG - Grupo FP OFICIAL.', link: 'https://3brincopg.com/?id=611505664&currency=BRL&type=2' },
  { id: 45, src: '/images/bebidas.jpg', name: 'Bebidas PG', info: 'Lançamento Bebidas PG - Grupo FP OFICIAL.', link: 'https://3bebidaspg.com/?id=992953543&currency=BRL&type=2' },
  { id: 46, src: '/images/familia.jpg', name: 'Familia PG', info: 'Lançamento Familia PG - Grupo FP OFICIAL.', link: 'https://3familiapg.com/?id=995752130&currency=BRL&type=2' },
  { id: 47, src: '/images/graca.jpg', name: 'Graça PG', info: 'Lançamento Graça PG - Grupo FP OFICIAL.', link: 'https://3gracapg.com/?id=534581157&currency=BRL&type=2' },
  { id: 48, src: '/images/petala.jpg', name: 'Petala PG', info: 'Lançamento Petala PG - Grupo FP OFICIAL.', link: 'https://3petalapg.com/?id=910064537&currency=BRL&type=2' },
  { id: 49, src: '/images/cilios.jpg', name: 'Cilios PG', info: 'Lançamento Cilios PG - Grupo FP OFICIAL.', link: 'https://3ciliospg.com/?id=516614416&currency=BRL&type=2' },
  { id: 50, src: '/images/gesto.jpg', name: 'Gesto PG', info: 'Lançamento Gesto PG - Grupo FP OFICIAL.', link: 'https://3gestopg.com/?id=640726942&currency=BRL&type=2' },
  { id: 51, src: '/images/vestidopg.jpeg', name: 'Vestido PG', info: 'Lançamento Vestido PG - Grupo FP OFICIAL', link: 'https://vestidopg.com/?id=393399020&currency=BRL&type=2' },
  { id: 52, src: '/images/fofoca.jpeg', name: 'Fofoca PG', info: 'Lançamento Fofoca PG - Grupo FP OFICIAL.', link: 'https://6fofocapg.com/?id=647705279&currency=BRL&type=2' },
  { id: 53, src: '/images/celine.jpg', name: 'Celine PG', info: 'Lançamento Celine PG - Grupo FP OFICIAL.', link: 'https://7celinepg.com/?id=812109725&currency=BRL&type=2' },
  { id: 54, src: '/images/loiropg.jpeg', name: 'Loiro PG', info: 'Lançamento Loiro PG - Grupo FP OFICIAL.', link: 'https://loiropg.com/?id=186554643&currency=BRL&type=2' },
  { id: 55, src: '/images/ondapg.jpeg', name: 'Onda PG', info: 'Lançamento Onda PG - Grupo FP OFICIAL.', link: 'https://ondaspg.com/?id=641736121&currency=BRL&type=2' },
]



export const randomPhrases = [
  "A mais compatível com você neste momento.",
  "Perfeito para o seu momento!",
  "A melhor opção do dia!",
  "Sorte está no ar para você, esta é a plataforma recomendada!",
  "O destino está ao seu lado, achamos uma plataforma para você!",
  "A escolha perfeita para vencer!",
  "Hoje é o seu dia de sorte!",
  "Não perca essa oportunidade de vitória!"
];